build: correct log directory creation and permission settings

diff --git a/pishoo/pkg/debian/postinst b/pishoo/pkg/debian/postinst
--- a/pishoo/pkg/debian/postinst
+++ b/pishoo/pkg/debian/postinst
@@ -5,21 +5,21 @@ LOG_DIR="/var/log/pishoo"
 LOG_PERMISSIONS="755"
 
 case "$1" in
-  configure|configure-in-favour)
+  configure)
         if [ ! -d "$LOG_DIR" ]; then
             mkdir -p "$LOG_DIR"
             if [ $? -ne 0 ]; then
                 echo "Failed to create log directory $LOG_DIR" >&2
                 exit 1
             fi
+
+            chmod $LOG_PERMISSIONS "$LOG_DIR"
+            if [ $? -ne 0 ]; then
+                echo "Failed to set permissions on log directory $LOG_DIR" >&2
+                exit 1
+            fi
+          fi
         fi
-        chmod $LOG_PERMISSIONS "$LOG_DIR"
-        if [ $? -ne 0 ]; then
-            echo "Failed to set permissions on log directory $LOG_DIR" >&2
-            exit 1
-        fi
-    ;;
-  abort-upgrade|abort-remove|abort-deconfigure|configure)
     ;;
   triggered)
     if command -v systemctl > /dev/null 2>&1 && systemctl is-active --quiet pishoo; then
@@ -33,9 +33,10 @@ case "$1" in
     ;;
   *)
     echo "postinst called with unknown argument \`$1'" >&2
-    exit 1
     ;;
 esac
+
+#DEBHELPER#
 
 if command -v systemctl > /dev/null 2>&1 && systemctl is-active --quiet pishoo; then
   systemctl upgrade pishoo || systemctl restart pishoo
@@ -48,6 +49,5 @@ else
   exit 0
 fi
 
-#DEBHELPER#
 
 exit 0
